services:
  postgres:
    image: postgres:16-alpine
    container_name: focusboard-db
    environment:
      POSTGRES_DB: focusboard
      POSTGRES_USER: focusboard_user
      POSTGRES_PASSWORD: focusboard_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focusboard_user -d focusboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: focusboard-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: